# Numpy

In [3]:
# 新建数组
import numpy as np

x = np.array([1., 2., 3.])

print (x)

[1. 2. 3.]


In [23]:
type(x)

numpy.ndarray

In [24]:
# numpy的算术运算

y = np.array([2.0, 4.0, 6.0])

x+y

array([3., 6., 9.])

In [25]:
x*y

# 数组的元素对应相乘

array([ 2.,  8., 18.])

In [26]:
z = np.append(y,[12.]) # z是
z

array([ 2.,  4.,  6., 12.])

数组运算需要元素数相同

In [27]:
x*z # 数组运算需要元素数相同

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [29]:
# “对应元素的”的英文是 element-wise，比如“对应元素的乘法”就是 element-wise product

## 广播

NumPy 中，形状不同的数组之间也可以进行运算。之前的例子中，在 2×2 的矩阵 A 和标量 10 之间进行了乘法运算。在这个过程中，如下图所示，标量 10 被扩展成了 2 × 2 的形状，然后再与矩阵 A 进行乘法运算。这个巧妙的功能称为 广播 （broadcast）。

<img src= "Broadcast_1.PNG" >

In [4]:
A = np.array([[1, 2], [3, 4]])

B = np.array([10, 20])

A * B

array([[10, 40],
       [30, 80]])

在这个运算中，如下图所示，一维数组 B 被“巧妙地”变成了和二位数组 A 相同的形状，然后再以对应元素的方式进行运算。

<img src= "Broadcast_2.PNG" >

综上，因为 NumPy 有广播功能，所以不同形状的数组之间也可以顺利地进行运算。

将X转换为一维数组

In [10]:
A = A.flatten()
print(A)

[1 2 3 4]


In [11]:
# 数组作为索引

A[np.array([0, 2, 3])]

array([1, 3, 4])

对 NumPy 数组使用不等号运算符等，结果会得到一个布尔型的数组。下例中就是使用这个布尔型数组取出了数组的各个元素（取出 True 对应的元素）。

In [13]:
A>2

array([False, False,  True,  True])

In [15]:
A[A>2]

array([3, 4])